version: '3.2'

services:
#  elasticsearch:
#    image: elasticsearch:7.17.5
#    restart: unless-stopped
#    environment:
#      - xpack.license.self_generated.type=basic
#    volumes:
#      - type: bind
#        source: ./elasticsearch/config/elasticsearch.yml
#        target: /usr/share/elasticsearch/config/elasticsearch.yml
#        read_only: true
#      - type: volume
#        source: elasticsearch
#        target: /usr/share/elasticsearch/data
#    ports:
#      - "9200:9200"
#      - "9300:9300"
#    environment:
#      ES_JAVA_OPTS: "-Xmx16g -Xms16g"
#      ELASTIC_PASSWORD: ambgam35!
#      discovery.type: single-node
#    networks:
#      - elk

  logstash:
    image: logstash:7.17.5
    restart: unless-stopped
    deploy:
      resources:
        limits:
          # cpus: '2.0'
          memory: 16384M
    volumes:
      - type: bind
        source: ./logstash/config/logstash.yml
        target: /usr/share/logstash/config/logstash.yml
        read_only: true
      - type: bind
        source: ./logstash/pipeline
        target: /usr/share/logstash/pipeline
        read_only: true
    ports:
      - "5000:5000/tcp"
      - "5000:5000/udp"
      - "9600:9600"
      - "5044:5044"
      - "5045:5045"
    environment:
      LS_JAVA_OPTS: "-Xmx8g -Xms8g"
    networks:
      - elk
#    depends_on:
#      - elasticsearch

#  kibana:
#    image: kibana:7.17.5
#    restart: unless-stopped
#    volumes:
#      - type: bind
#        source: ./kibana/config/kibana.yml
#        target: /usr/share/kibana/config/kibana.yml
#        read_only: true
#    ports:
#      - "80:5601"
#    networks:
#      - elk
#    depends_on:
#      - elasticsearch

networks:
  elk:
    driver: bridge

#volumes:
#  elasticsearch:
